### ISSUE TITLE
What is the suggested way of using sessions in a production Spock web application?

### ISSUE THREAD

**Issue by sras** [agrafix/Spock#43]
I was using 'readShowSessionPersist' while developement. But now I am thinking about making the app live, I would like to know how to integrate production quality session management to my App. 

I saw can see the spc_load function [here](http://hackage.haskell.org/package/Spock-0.7.12.0/docs/Web-Spock-Shared.html#t:SessionCfg), but it seems that it expects to return the contents of every live sessions, which does not appear to be very efficient to me. 

What am I missing?

**Comment by agrafix** [comment]
Let's go step by step:

* There are two reasons why you should not use `readShowSessionPersist` in production: It can not handle migrations. If you decide to change your session type, your app will not launch anymore (`read` will fail). The second problem may be a performance issue for very large live session sets: We always write all living sessions to disk after each housekeeping step. This could result in a large IO and serialization overhead.

* `spc_load` is only called once when the application launches - that's why you will need to return all previous live sessions otherwise there's no way the session manager will known about them if you don't. This could be done incremental, but as it is only done once on launch this should not be a problem for most workloads. (If you hit a problem here, report a bug)

* `spc_store` is called on each housekeeping step. The optimal session-store would then perform a diff between its current state and the state returned by `spc_store` and apply the needed actions. It will only serialize sessions if changed or added. Session data should be serialized in a migratable way. This should be efficient enough for most workloads, if not we should think about making spc_store incremental and move to diff calculation into the `SessionManager` to happen on the fly.

* You should only store small data structures in your session (IDs, Tags, ...), as they will all be held in memory by the webserver

Does that help you?

**Comment by sras** [comment]
Actually I think I messed up somewhere.

When the first time I tried using sessions, leaving 'sc_persistCfg' as Nothing, it seemed that the session data was not getting persisted. So I figured I might have to pass the valid functions to actually persist the data in SessionPersistCfg data structure. So I looked around and found readShowSessionPersist, and when I tried passing it, every thing seemed to work. So I ended up having the impression that it is mandatory to implement/pass the functions to persist session. 

So let me confirm this. Spock already has 100% support for production quality sessions (Built on top of wai-session, I suppose). And there is no need to pass session persistence functions in sc_PersistCfg.  Functions in sc_PersistCfg are only meant to persist session data between server restarts and for housekeeping step. If I leave it blank, then session data will be lost between restarts and no housekeeping will be done. Is this correct?

Also, if I want to store the session data in the database instead of server memory, how can I do that?

Thanks.

**Comment by agrafix** [comment]
If you want to persist sessions between server runs, you will have to implement `sc_persistCfg`. If you leave it blank sessions will only live in memory until housekeeping clears them out or you kill your server process. 

If you want sessions to live in the database you will need to implement `sc_persistCfg` as described above.

**Comment by sras** [comment]
>until housekeeping clears them out

How often does this happen. And is this is regardless of sc_sessionTTL value?

**Comment by agrafix** [comment]
```haskell
data SessionCfg a
   = SessionCfg
   { -- ...
   , sc_sessionTTL :: NominalDiffTime
     -- ^ how long should a client session live
   , sc_sessionExpandTTL :: Bool
     -- ^ if this is true, every page reload will renew the session time to live counter
   , sc_housekeepingInterval :: NominalDiffTime
     -- ^ how often should the session manager check for dangeling dead sessions
    -- ...
   }
```

Every `sc_housekeepingInterval` we will check if a sessions age is larget than `sc_sessionTTL`. If yes, it will be removed. If `sc_sessionExpandTTL`  is set to true, the sessions age will be reset on each read.

**Comment by sras** [comment]
Oh. I am sorry. Apparently I was checking the outdated code for the [sample project](https://github.com/agrafix/funblog/blob/2504c98c31c87e2d03812152aa1c25ad0e8252e0/src/Web/Blog.hs).

Thanks for your time and for a fantastic framework. I will close the issue now.

**Comment by agrafix** [comment]
You are right, funblog should be updated. If you like you can submit a pull request or report a bug there.
