### ISSUE TITLE
Can't get CSRF working

### ISSUE THREAD

**Issue by dbushenko** [agrafix/Spock#59]
I'm trying to compile the example from the documentation but all the time have errors. The last one looks like this:

Expected type: Int -> ActionCtxT () (WebStateM conn0 sess0 st0) ()
      Actual type: hvect-0.2.0.0:Data.HVect.HVectElim
                     '[Int] (ActionCtxT () IO ())

I'm not saying that Spock works wrong, but at least something should be done with the documentation. Also one comprehensive example would be very nice!

**Comment by agrafix** [comment]
Could you please provide a Short, Self Contained, Correct (Compilable), Example (http://sscce.org/)?

**Comment by dbushenko** [comment]
No, I can't provide  you correct (compilable) example since the issue is: I can't compile the example from your documentation.

This is what I'm doing: https://gist.github.com/dbushenko/ec4f34d0799c844c7ac9

**Comment by agrafix** [comment]
The code you've provided has a different issue: Looking a the types of `spockT`, `get` and `safeActionPath` the latter requires a specialized `ActionT` (=> `SpockAction`), while `spockT` and `get` inside `spockT` will only provide a generalized `ActionT`. You should use `spock` instead of `spockT` and all should work well! I'm trying to make this more clear in the docs (see #57 )

**Comment by dbushenko** [comment]
Thanks!
